name: Lint Check

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # ---- Backend Lint ----
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend lint
        working-directory: ./backend
        run: npm run lint

      # ---- Frontend Lint ----
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend lint
        working-directory: ./frontend
        run: npm run lint
